// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	"github.com/aql-lang/aql/eng"
	sdk "github.com/voxgig-sdk/maplestory-sdk/go"
)

// registerSDKWords installs three native AQL words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word.
func registerSDKWords(r *eng.Registry, client *sdk.MaplestorySDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.NativeSig{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		dual := eng.NativeSig{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:        op,
			ForwardArgs: true,
			Signatures:  []eng.NativeSig{single, dual},
		})
	}
}

func runOp(client *sdk.MaplestorySDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.MaplestorySDK, name string) (sdk.MaplestoryEntity, error) {
	switch strings.ToLower(name) {
	case "android":
		return client.Android(nil), nil
	case "avatar":
		return client.Avatar(nil), nil
	case "cache":
		return client.Cache(nil), nil
	case "character":
		return client.Character(nil), nil
	case "chat":
		return client.Chat(nil), nil
	case "cluster":
		return client.Cluster(nil), nil
	case "diff":
		return client.Diff(nil), nil
	case "entity1":
		return client.Entity1(nil), nil
	case "gms_new":
		return client.GmsNew(nil), nil
	case "guild_mark":
		return client.GuildMark(nil), nil
	case "health":
		return client.Health(nil), nil
	case "item":
		return client.Item(nil), nil
	case "job":
		return client.Job(nil), nil
	case "map":
		return client.Map(nil), nil
	case "metric":
		return client.Metric(nil), nil
	case "mob":
		return client.Mob(nil), nil
	case "music":
		return client.Music(nil), nil
	case "name":
		return client.Name(nil), nil
	case "npc":
		return client.Npc(nil), nil
	case "nxf":
		return client.Nxf(nil), nil
	case "performance_metric":
		return client.PerformanceMetric(nil), nil
	case "pet":
		return client.Pet(nil), nil
	case "quest":
		return client.Quest(nil), nil
	case "system":
		return client.System(nil), nil
	case "tip":
		return client.Tip(nil), nil
	case "wzn":
		return client.Wzn(nil), nil
	case "wzn2":
		return client.Wzn2(nil), nil
	case "wzn3":
		return client.Wzn3(nil), nil
	case "wzn4":
		return client.Wzn4(nil), nil
	case "wzn5":
		return client.Wzn5(nil), nil
	case "wzn6":
		return client.Wzn6(nil), nil
	case "z_map":
		return client.ZMap(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts an AQL Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.VType.Matches(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.VType.Matches(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.VType)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
