// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/maplestory-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"android | avatar | cache | character | chat | cluster | diff | entity1 | gms_new | guild_mark | health | item | job | map | metric | mob | music | name | npc | nxf | performance_metric | pet | quest | system | tip | wzn | wzn2 | wzn3 | wzn4 | wzn5 | wzn6 | z_map"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.MaplestorySDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "maplestory_list",
		Description: "List records from Maplestory. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "maplestory_load",
		Description: "Load a single record from Maplestory. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.MaplestorySDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.MaplestorySDK, name string) (sdk.MaplestoryEntity, error) {
	switch strings.ToLower(name) {
	case "android":
		return client.Android(nil), nil
	case "avatar":
		return client.Avatar(nil), nil
	case "cache":
		return client.Cache(nil), nil
	case "character":
		return client.Character(nil), nil
	case "chat":
		return client.Chat(nil), nil
	case "cluster":
		return client.Cluster(nil), nil
	case "diff":
		return client.Diff(nil), nil
	case "entity1":
		return client.Entity1(nil), nil
	case "gms_new":
		return client.GmsNew(nil), nil
	case "guild_mark":
		return client.GuildMark(nil), nil
	case "health":
		return client.Health(nil), nil
	case "item":
		return client.Item(nil), nil
	case "job":
		return client.Job(nil), nil
	case "map":
		return client.Map(nil), nil
	case "metric":
		return client.Metric(nil), nil
	case "mob":
		return client.Mob(nil), nil
	case "music":
		return client.Music(nil), nil
	case "name":
		return client.Name(nil), nil
	case "npc":
		return client.Npc(nil), nil
	case "nxf":
		return client.Nxf(nil), nil
	case "performance_metric":
		return client.PerformanceMetric(nil), nil
	case "pet":
		return client.Pet(nil), nil
	case "quest":
		return client.Quest(nil), nil
	case "system":
		return client.System(nil), nil
	case "tip":
		return client.Tip(nil), nil
	case "wzn":
		return client.Wzn(nil), nil
	case "wzn2":
		return client.Wzn2(nil), nil
	case "wzn3":
		return client.Wzn3(nil), nil
	case "wzn4":
		return client.Wzn4(nil), nil
	case "wzn5":
		return client.Wzn5(nil), nil
	case "wzn6":
		return client.Wzn6(nil), nil
	case "z_map":
		return client.ZMap(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
